In [1]:
import numpy as np

In [2]:
#create array

df=np.array([1,2,3,4,5]) # 1D array (vector)
df

array([1, 2, 3, 4, 5])

In [3]:
type(df)

numpy.ndarray

In [4]:
df.shape

(5,)

In [5]:
df2=np.array([1,2,3,4,5]) 
df2.reshape(1,5) # 2D array  5 column 1 row matris



array([[1, 2, 3, 4, 5]])

In [6]:
df2.reshape(5,1) # 2D array  1 column 5 row matris

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
df3=np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
df3.shape

(2, 5)

In [8]:
df4=np.arange(1,10,2).reshape(5,1)
df4

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [9]:
d5=np.ones((5,1))
d5

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [10]:
#identitiy matrix
np.eye(3)#3x3 I matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
array=np.array([[1,2,3],[4,5,6]])
print(f'array:\n{array}')
print(f'shape:{array.shape}')
print(f'dimension:{array.ndim}')
print(f'size:{array.size}')
print(f'data type:{array.dtype}')
print(f'item size in bytes:{array.itemsize}')






array:
[[1 2 3]
 [4 5 6]]
shape:(2, 3)
dimension:2
size:6
data type:int32
item size in bytes:4


In [12]:
##vectorized operations
array1=np.array([1,2,3,4,5,6])
array2=np.array([10,20,30,40,50,60])

print('addition',array1+array2)
print('substraction',array2-array1)
print('multiplication',array1*array2)
print('division',array2/array1)


addition [11 22 33 44 55 66]
substraction [ 9 18 27 36 45 54]
multiplication [ 10  40  90 160 250 360]
division [10. 10. 10. 10. 10. 10.]


In [13]:
##universal function (which is for every variable in array)
array1=np.array([1,2,3,4,5,6])
#square root
print('square root',np.sqrt(array1))
#exponential
print('exponential',np.exp(array1))
#sine
print('sine',np.sin(array1)) ###RADIAN
#log
print('log',np.log(array1))


'''
arr = np.array([30, 40])
arr_radians = np.radians(arr)  # degree to radian 
sin_values = np.sin(arr_radians)
'''  



square root [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
exponential [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
sine [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
log [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


'\narr = np.array([30, 40])\narr_radians = np.radians(arr)  # degree to radian \nsin_values = np.sin(arr_radians)\n'

In [14]:
#slicing and indexing

array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('array:\n',array,'\n')
print('first row first element',array[0][0])
print('first row second element',array[0][1])

print('i want to get 7 8 11 12')
print(array[1:,2:])
print('i want to get 3 4 7 8')
print(array[0:2,2:]) #(0 ve 1. Satır 2 dahil değil) ve 2. sütundan itibaren tüm sütunların seçilmesini sağlar.



array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

first row first element 1
first row second element 2
i want to get 7 8 11 12
[[ 7  8]
 [11 12]]
i want to get 3 4 7 8
[[3 4]
 [7 8]]


In [20]:
# İlk ve üçüncü satırı (0. ve 2. indeks), ilk iki sütunu (0 ve 1. indeks) al
result = array[[0, 2], :2]
result

array([[ 1,  2],
       [ 9, 10]])

In [27]:
# 6 7 9 10
res=array[[1,2],1:3]
res


array([[ 6,  7],
       [10, 11]])

In [29]:
#second method
print(array[1:,1:3])

[[ 6  7]
 [10 11]]


In [ ]:
###normalization
## have a mean of 0 and standart devation of 1

In [ ]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

mean=np.mean(data)
print('mean:',mean)
median=np.median(data) #Sıralanmış veri kümesinde ortada bulunan değerdir.

#Eğer eleman sayısı tek ise → Tam ortadaki eleman alınır.
#Eğer eleman sayısı çift ise → Ortadaki iki elemanın ortalaması alınır.

print('median:',median)
standartdviation=np.std(data)
print('standartdviation:',standartdviation)
# Verilerin ortalamadan ne kadar sapma gösterdiğini ölçer. Daha büyük bir standart sapma, verilerin daha yaygın olduğunu gösterir.


variance=np.var(data)
print('variance:',variance)
#Varyans, standart sapmanın karesi olup, verilerin ortalamaya göre ne kadar değiştiğini gösterir.




mean: 5.5
median: 5.5
standartdviation: 2.8722813232690143
variance: 8.25


In [35]:
#logical operation 

data=np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5] 

array([ 6,  7,  8,  9, 10])

In [36]:
data[data>10] 

array([], dtype=int32)

In [39]:
data[(data>5) & (data<10)] 

array([6, 7, 8, 9])